
package comp3350.team8.inventorymanagement.object;


public class Product
{
	public static final int DEFAULT_ID = -1; // place-holder ID for new products whose ProductIDs haven't been calculated
	public static final double SP_NOT_GIVEN = 0.9; // default supplierPrice(ratio to actual price);
	public static final int LS_NOT_GIVEN = 5; // default Low Stock value;
	
	private int		productId;
	private String	name;
	private String	description;
	private double	price;
	private double	supplierPrice;
	private int		quantity;
	private int 	lowStock;
	
	// it is used for create new product by customer
	public Product(String name, String description, double price, int quantity)
	{
		this(name, description, price, price * SP_NOT_GIVEN, quantity, LS_NOT_GIVEN);
		
	}

	// it is used for get product from database, the productId generated by the
	// database
	// since it is the primary key
	public Product(int productId, String name, String description,
			double price, int quantity)
	{
		this(productId, name, description, price, SP_NOT_GIVEN * price, quantity, 0);
		//this.productId = productId;
	}
	
	public Product(int productId, String name, String description,
			double price, int quantity, int lowStock)
	{
		this(productId, name, description, price, 
				price * SP_NOT_GIVEN, quantity, lowStock);
	}
	
	public Product(int productId, String name, String description, double price, double supplierPrice, int quantity, int lowStock)
	{
		this.productId = productId;
		this.name = name;
		this.description = description;
		this.setPrice( price );
		this.setQuantity( quantity );
		this.lowStock = lowStock;
		this.supplierPrice = supplierPrice;

	}
	
	public Product(String name, String description, double price, double supplierPrice, int quantity, int lowStock)
	{
		this(DEFAULT_ID, name, description, price, supplierPrice, quantity, lowStock);
	}
	
	public Product clone()
	{
		
		Product product = new Product( this.productId, this.name,
				this.description, this.price, this.supplierPrice, this.quantity, this.lowStock );
		return product;
	}
	
	public int getProductId()
	{
		return this.productId;
	}
	
	public String getName()
	{
		return this.name;
	}
	
	public String getDescription()
	{
		return this.description;
	}
	
	public double getPrice()
	{
		return this.price;
	}
	
	public int getQuantity()
	{
		return this.quantity;
	}
	
	public int getLowStock(){
		return this.lowStock;
	}
	
	public double getCost(){
		return this.supplierPrice;
	}
	
	public void setProductId(int Id)
	{
		this.productId = Id;
	}
	
	public void setName(String name)
	{
		this.name = name;
	}
	
	public void setDescription(String description)
	{
		this.description = description;
	}
	
	public void setPrice(double price)
	{
		this.price = ( price >= 0 ) ? price : 0;
	}
	
	public void setQuantity(int quantity)
	{
		this.quantity = ( quantity >= 0 ) ? quantity : 0;
	}
	
	public void setLowStock(int low){
		lowStock = low;
	}
	
	public void setCost(double cost){
		supplierPrice = cost;
	}
	
	public boolean isLow(){
		return quantity <= lowStock;
	}
	
	// it is used for ArrayList indexOf method to search data
	public boolean equals(Object object){
		boolean result = false;
		Product product;
		
		if (object instanceof Product)
		{
			product = (Product) object;
			result =  (this.productId != DEFAULT_ID) && (product.productId == this.productId);
			// if a product hasn't yet received its ID from the database, we don't know if these two are the same;
			// return false
		}
		
		return result;
	}
}
